[package]
name = "badsv"
version = "0.1.0"
authors = ["RocketRace <neverquitben@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
clap = "2.33"
csv = "1.1"